language: csharp
solution: sharpberry.sln
install:
  - nuget restore sharpberry.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release sharpberry.sln
  - find . -name '*.tests.dll' | grep bin | xargs -i mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe {} /exclude:Integration
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Rh0Lz7hvAX31/u56ru14dhPJAxLW7Bf1N4oZiS63yYIOy/9CqmVIJT8Yqu5ow+e6YZWVI+CuNnKhNMDw86BPXkye72NCv1im0stsWk4Xf+sc3d/Mt/PhAYmRtOXXoafhyEUVme7AVj5PDupsmphrIfUsOavl+LLzUfIcLLZ8UW/NWQX0/OLB7A/oAlb5JlXxh8ALUG9Pr5WEdQsWCXtSOZGLxjsrGIs4TlqT8iU/3iekji7ZId8ebawTAysRefduXwzt+CW22y7gwUobKIiyIywSlKjVAsfH3sYiEJaG8jtXMvl7ikCAbMnMIyLGjFL1NCNLX4DOd2+LzErpi/3ECQI2W+0+uosqQF00ntLaNscWEExNT2BfQGUxrutN2U6jmB1Zs3NPBv/YoNJrYOpkm4OLr6Wy6XA53kMD32l4c+cUjfOBRzIciWcT1xm+S5NfMY4GVeEPSSDn+ubH+pVvdX773MAmO3d85mQYgFo/ndmv16e9HDAGD1gNa/IrYMTL7qBsQ9DDxmF60A7csxuuW9LcTNB+e9d39D9Z3YQSY1M4e9mc7vgaVQda7Ri8OBpIbexKle2FGQ2Yq/MISasxTPm7rc0P5WfRw+nEfKXvbJMbkZlr9ltDGv99VRpdWtMT2+FZLe5CyjJ721acW8Pu9upaAasbD2vF4uB2WdmeLQU="

addons:
  coverity_scan:
    project:
      name: "chrispyduck/sharpberry"
      description: "Raspberry Pi-based vehicle black box"
    build_command_prepend: "nuget restore sharpberry.sln"
    build_command:   "xbuild /p:Configuration=Release sharpberry.sln"
    branch_pattern: coverity_scan